[package]
name = "adventofcode24"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.9"
indicatif = "0.17.9"
crossbeam = "0.8"
regex = "1.11.1"
colored = "*"
itertools = "*"
